version: 2.1

commands:
  change-workdir:
    parameters:
      path:
        default: /root/project
        type: string
    steps:
      - run:
          name: "Check new directory"
          command: mkdir -p <<parameters.path>>
      - run:
          name: "Change directory"
          command: cd <<parameters.path>> && pwd && ls -ls
jobs:
  build-recipes:
    docker:
      - image: balena/yocto-build-env:24b1d67

    steps:
      - run:
          name: "Get env"
          command: "env"
      - change-workdir
      - checkout:
          path: ${CIRCLE_WORKING_DIRECTORY}/meta-motur
      - change-workdir
      - run:
          name: "Get env"
          command: "env"
      - run:
          name: "Setup"
          command: |
                   chmod +x ${CIRCLE_WORKING_DIRECTORY}/meta-motur/scripts/setup.sh && \
                   ${CIRCLE_WORKING_DIRECTORY}/meta-motur/scripts/setup.sh ${CIRCLE_WORKING_DIRECTORY}
      - change-workdir

workflows:
  motur-workflow:
    jobs:
      - build-recipes
