version: 2.1


jobs:
  build-recipes:
    docker:
      - image: balena/yocto-build-env:24b1d67

    steps:
      - run:
          name: "Directory structure"
          command: "mkdir meta-motur && cd meta-motur"
      - checkout
      - run:
          name: "Env info"
          command: "cd ${CIRCLE_WORKING_DIRECTORY} && pwd && ls -ls && env"
      - run:
          name: "Setup"
          command: "${CIRCLE_WORKING_DIRECTORY}/meta-motur/scripts/setup.sh"

workflows:
  motur-workflow:
    jobs:
      - build-recipes
