version: 2.1

commands:
  change-workdir:
    parameters:
      path:
        default: "${CIRCLE_WORKING_DIRECTORY}"
        type: string
    steps:
      - run:
          command: "cd ${CIRCLE_WORKING_DIRECTORY} && pwd && ls -ls && env"
jobs:
  build-recipes:
    docker:
      - image: balena/yocto-build-env:24b1d67

    steps:
      - run:
          name: "Prepare structure"
          command: "mkdir meta-motur && cd meta-motur"
      - checkout
      - change-workdir
      - run:
          name: "Setup"
          command: "${CIRCLE_WORKING_DIRECTORY}/meta-motur/scripts/setup.sh"
      - change-workdir

workflows:
  motur-workflow:
    jobs:
      - build-recipes
