version: 2.1

commands:
  change-workdir:
    parameters:
      path:
        default: /home/admin/project
        type: string
    steps:
      - run:
          name: "Check new directory"
          command: mkdir -p <<parameters.path>>
      - run:
          name: "Change directory"
          command: cd <<parameters.path>> && pwd && ls -ls
jobs:
  build-recipes:
    docker:
      - image: macandkaj/yocto-motur-env:44a7adbb9e55
        user: admin

    steps:
      - run:
          name: "Environment"
          command: env
      - change-workdir
      - checkout:
          path: /home/admin/project/meta-motur
      - change-workdir
      - run:
          name: "Prepare scripts"
          command: |
              pwd && ls -ls \
              chmod +x /home/admin/project/meta-motur/scripts/setup.sh && \
              chmod +x /home/admin/project/meta-motur/scripts/build_target.sh
      - run:
          name: "Setup"
          command: |
              pwd && ls -ls \
              /home/admin/project/meta-motur/scripts/setup.sh /home/admin/project
      - change-workdir
      - run:
          name: "Build motoros-interfaces"
          command: |
              pwd && ls -ls \
              /home/admin/project/meta-motur/scripts/build_target.sh \
              -p /home/admin/project \
              -m qemuarm64 \
              -t motoros-interfaces
workflows:
  motur-workflow:
    jobs:
      - build-recipes
